pattern_cols: 10
pattern_rows: 7
center_distance_mm: 18

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "mindvision"
exposure_ms: 3
gain: 10.0
gamma: 0.5
vid_pid: "f622:d206"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "vcan0"
